### PR TITLE
Bootstrap with Containerbuddy

### PR DESCRIPTION
**Pull request by tgross**
@misterbisson this PR simplifies the bootstrapping of Consul by using Containerbuddy health checks to join a cluster that's been primed with `-bootstrap-expect`.

Our new `start.sh` script starts one instance w/ `BOOTSTRAP_HOST` unset and then uses that host IP for `BOOTSTRAP_HOST` on subsequent scale-ups. _Any_ Consul host IP can be swapped in for the value of `BOOTSTRAP_HOST` at any future time. When an instance does its health check, it checks to see if it's already a member of a raft. If not, it checks if it has the env var `BOOTSTRAP_HOST` set. If not, it starts the raft by joining itself. If so, it joins the `BOOTSTRAP_HOST`.

This results in the following timeline:
- first node `consul_1` starts
- on first health check `consul_1`:
  - uses `consul info` to see it has no raft peers
  - checks `BOOTSTRAP_HOST` and finds it empty
  - `consul join`s itself
- we then start `consul_2` and `consul_3`:
- on first health check, each one:
  - uses `consul info` to see it has no raft peers
  - checks `BOOTSTRAP_HOST` and finds the IP for `consul_1`
  - `consul join`s that IP
- we now have a healthy raft
- on subsequent health checks, each healthy consul node:
  - uses `consul info` to see it has peers
  - returns 0 to Containerbuddy's health check and Containerbuddy writes the TTL
- on subsequent health checks, each _unhealthy_ consul node:
  - uses `consul info` to see it has no peers
  - tries to rejoin the raft
    - if the `BOOTSTRAP_HOST` has been killed or is unreachable, the node will still be using Consul gossip protocol to attempt to rejoin on its own

The advantages of this approach are:
- way less bash to write
- no links
- no node is special except for the first node, and even then only at bootstrap time (which means it can be replaced)

### CODE REVIEW

**Comment by misterbisson** [comment]
I like this, and have to admit that I hadn't really thought about changing the env var after starting the first one. I'd like to test what happens if `consul_1` reboots, though. Because it will restart without `BOOTSTRAP_HOST` set, it could attempt to form a new raft, leading to a split brain scenario, no? What happens if both `consul_1` and `consul_2` reboot? That would lead to a very split brain, yes?

**Comment by tgross** [comment]
A lot of the cluster state is maintained on disk, so the scenario may not be quite that dire. But I think the best way to ensure that is going to be to build a little test rig that starts the cluster, creates various conditions, and verifies the state of the raft after each condition. I'll have something later today.

**Comment by tgross** [comment]
I've re-read https://www.consul.io/docs/internals/consensus.html and given that, here's the conditions I'll demonstrate.

Note that in [his post on raft systems](https://aphyr.com/posts/316-call-me-maybe-etcd-and-consul) Kyle Kingsbury demonstrated a consistency flaw when an isolated leader self-elected; this was worked-around in Consul by Hashicorp now providing 3 kinds of reads -- `stale`, `default`, and `consistent`. The `default` read is the old "consistent" and is subject to that problem. In order to reliably test _our_ system and not raft's algorithm gaps, I'll use only either `stale` or `consistent` reads, never `default`.

3 node raft:
- stop `consul_3`
  - verify election takes place, if necessary
  - verify `consul_1` and `consul_2` accept writes
  - verify those writes with `consistent` reads (we still have quorum)
  - restart `consul_3`
    - verify it rejoins existing raft
- stop `consul_1`
  - verify election takes place, if necessary
  - restart `consul_1`
    - verify it rejoins existing raft
- stop `consul_1`, stop `consul_3`
  - start `consul_3`
    - verify it rejoins existing raft
  - start `consul_1`
    - verify it rejoins existing raft

5 node raft:
- stop `consul_1`, stop `consul_2`, stop `consul_3`
  - verify remaining nodes accept writes
  - verify those writes with `stale` reads
  - verify that `consistent` reads of those same writes now fail (there's no quorum)
  - start `consul_2`
    - verify `consul_2` rejoins raft
    - verify that `consistent` reads of the previous writes succeed (there's a quorum)
  - start `consul_1`
    - verify `consul_1` rejoins raft
- use IP tables filters to netsplit into a `consul_1`+`consul_2` and a `consul_3`+`consul_4`+`consul_5` group.
  - send different writes to both groups
  - heal the netsplit
  - verify the raft reforms and that our majority writes win

**Comment by tgross** [comment]
@misterbisson I've pushed commits that get the 3 node test into working order. Here's what an example test run looks like:

``` bash
$ make test
node ./raft-test.js
Running 3-node raft tests.
Bootstrap node is: consul_consul_1
expected peers: 192.168.128.173:8300,192.168.128.174:8300,192.168.128.175:8300
raft leader is among expected nodes
raft is healthy:  true
[test3_1] -----------------------------
stopping consul_consul_3
expected peers: 192.168.128.173:8300,192.168.128.174:8300
raft leader is among expected nodes
starting consul_consul_3
expected peers: 192.168.128.173:8300,192.168.128.174:8300,192.168.128.175:8300
raft leader is among expected nodes
[test3_2] -----------------------------
stopping consul_consul_1
expected peers: 192.168.128.174:8300,192.168.128.175:8300
raft leader is among expected nodes
starting consul_consul_1
expected peers: 192.168.128.173:8300,192.168.128.174:8300,192.168.128.175:8300
raft leader is among expected nodes
[test3_3] -----------------------------
stopping consul_consul_1
stopping consul_consul_3
starting consul_consul_3
expected peers: 192.168.128.174:8300,192.168.128.175:8300
raft leader is among expected nodes
starting consul_consul_1
expected peers: 192.168.128.173:8300,192.168.128.174:8300,192.168.128.175:8300
raft leader is among expected nodes
Passed!
```

In terms of rigor of this test for HA, one gap is that we're not testing all the nodes for their leader individually. In a second pass, I'll probably want to ensure we know which node was the leader and ensure that it was killed to force elections. But as far as ensuring the BOOTSTRAP_NODE behavior is as we expected, this demonstrates it.

**Comment by misterbisson** [comment]
Let's merge it, but the readme will need some updates, no?

**Comment by tgross** [comment]
> Let's merge it, but the readme will need some updates, no?

Oops, yup. Let me hit that.

**Comment by tgross** [comment]
Done, @misterbisson

**Comment by misterbisson** [comment]
:house_with_garden: :walking:

**Pull request merged**
