### PR TITLE
Functional testing

### PR DESCRIPTION
**Pull request by tgross**
This is the work-in-progress PR for building a test rig for this repo that will run in our CI system.

cc @misterbisson as an FYI

### CODE REVIEW

**Comment by misterbisson** [comment]
lgtm

**Comment by tgross** [comment]
Sample output for what I've got so far:

```
----------------------------------------------------------------------
ConsulStackFiveNodeTest.test_rejoin_raft
----------------------------------------------------------------------
elapsed  | task
8.486596 | docker-compose -f docker-compose.yml -p consul stop
15.67022 | docker-compose -f docker-compose.yml -p consul rm -f
41.26930 | docker-compose -f docker-compose.yml -p consul up -d
5.133477 | docker-compose -f docker-compose.yml -p consul ps
88.20251 | docker-compose -f docker-compose.yml -p consul scale consul=5
9.287161 | docker-compose -f docker-compose.yml -p consul ps
9.287541 | settle: 5
1.432555 | docker inspect consul_consul_1
4.077545 | converge: 5
17.67312 | docker restart consul_consul_1
9.251753 | docker-compose -f docker-compose.yml -p consul ps
9.252086 | settle: 5
10.87522 | converge: 5
```

**Comment by misterbisson** [comment]
Is the "elapsed" the duration of the task?

**Comment by tgross** [comment]
> Is the "elapsed" the duration of the task?

Correct. Duration in seconds from the start of the call to when it returns (and the return value is parsed in Python, but that's teeny-tiny stuff like <1ms).

**Comment by tgross** [comment]
Closing this PR on my fork so I can get this branch built on Jenkins.

**Pull request closed without merging**
