### PR TITLE
Update consul, ContainerPilot, alpine versions

### PR DESCRIPTION
**Pull request by geek**

### CODE REVIEW

**Comment by misterbisson** [comment]
Changes look good. If it tests good, merge it.

**Comment by geek** [comment]
@misterbisson the tests seemed broken, I updated them, but want to wait for @tgross to provide a review before I publish.

**Review by tgross — COMMENTED** [review]
Just to clarify @geek it doesn't seem like this fixes the tests?
ref https://github.com/autopilotpattern/consul/issues/27

```
$ make test
node ./raft-test.js
Running 3-node raft tests.
Bootstrap node is: consul_consul_1
expected peers: 172.18.0.2:8300,172.18.0.3:8300,172.18.0.4:8300
raft leader is among expected nodes
raft is healthy:  true
[test3_1] -----------------------------
stopping consul_consul_3
expected peers: 172.18.0.2:8300,172.18.0.3:8300
error: raft leader is not among expected nodes
``

**Comment by geek** [comment]
@tgross :/ they seem a bit flaky. I am able to get to the last test step with these updates. Previously, the peer addresses weren't found correctly and the tests wouldn't wait for instances to start.

**Comment by tgross** [comment]
LGTM.

**Pull request merged**
