### PR TITLE
Test deploy improvements

### PR DESCRIPTION
**Pull request by tgross**
This PR mirrors the work done in https://github.com/autopilotpattern/nginx/pull/52, but for Consul.

TODO for completion:
- [x] two more tests to port
- [x] implement `make compose/test`
- [x] update README

### CODE REVIEW

**Comment by tgross** [comment]
What the tests look like so far:

```
$ make test/triton
docker run --rm \
                -e TAG=branch-test_deploy_improvements \
                -e TRITON_PROFILE=us-sw-1 \
                -e GIT_BRANCH=test_deploy_improvements \
                -v ~/.ssh:/root/.ssh:ro \
                -v ~/.triton/profiles.d:/root/.triton/profiles.d:ro \
                -w /src \
                autopilotpattern/consul-testrunner:branch-test_deploy_improvements /src/triton.sh

------------------------------------------------
setting up profile for tests
------------------------------------------------

"us-sw-1" is already the current profile
DOCKER_HOST=tcp://us-sw-1.docker.joyent.com:2376
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=[redacted]
SDC_URL=https://us-sw-1.api.joyent.com
SDC_ACCOUNT=[redacted]
SDC_KEY_ID=[redacted]
TRITON_PROFILE=us-sw-1

------------------------------------------------
executing rejoin-raft test with 3 nodes
------------------------------------------------

* cleaning up previous test run

No stopped containers

* standing up initial test targets

Creating consul_consul_1

* scaling up cluster

Creating and starting consul_consul_2 ...
Creating and starting consul_consul_3 ...
waiting for 3 Consul containers to be Up...one
stty: standard input: Not a tty
3 instances reported Up in <= 0 seconds
waiting for raft w/ 3 instances to converge...
raft converged in <= 0 seconds w/ leader 192.168.128.236:8300
consul_consul_1
waiting for 3 Consul containers to be Up...
stty: standard input: Not a tty
3 instances reported Up in <= 0 seconds
waiting for raft w/ 3 instances to converge...
raft converged in <= 0 seconds w/ leader 192.168.128.224:8300

------------------------------------------------
executing rejoin-raft test with 5 nodes
------------------------------------------------

* cleaning up previous test run

Stopping consul_consul_3 ...
Stopping consul_consul_2 ...
Stopping consul_consul_1 ...
Going to remove consul_consul_3, consul_consul_2, consul_consul_1
Removing consul_consul_3 ...
Removing consul_consul_2 ...
Removing consul_consul_1 ...
Removing consul_consul_1 ... done

* standing up initial test targets

Creating consul_consul_1

* scaling up cluster

Creating and starting consul_consul_2 ...
Creating and starting consul_consul_3 ...
Creating and starting consul_consul_4 ...
Creating and starting consul_consul_5 ...
waiting for 5 Consul containers to be Up...one
stty: standard input: Not a tty
5 instances reported Up in <= 0 seconds
waiting for raft w/ 5 instances to converge...
raft converged in <= 0 seconds w/ leader 192.168.128.217:8300
consul_consul_1
waiting for 5 Consul containers to be Up...
stty: standard input: Not a tty
5 instances reported Up in <= 0 seconds
waiting for raft w/ 5 instances to converge...
raft converged in <= 0 seconds w/ leader 192.168.128.217:8300

* tearing down containers

Stopping consul_consul_4 ...
Stopping consul_consul_3 ...
Stopping consul_consul_2 ...
Stopping consul_consul_5 ...
Stopping consul_consul_1 ...
Going to remove consul_consul_4, consul_consul_3, consul_consul_2, consul_consul_5, consul_consul_1
Removing consul_consul_4 ...
Removing consul_consul_3 ...
Removing consul_consul_2 ...
Removing consul_consul_5 ...
Removing consul_consul_1 ...
Removing consul_consul_4 ... done
------------------------------------------------
PASSED!
```

**Comment by jwreagor** [comment]
At first I didn't realize the test was using local docker so when I ran `make test/triton` I received the proverbial `host volumes are not supported` message.

Having unset my docker env vars I was able to at least build the test container but then received the following...

I take it the `FAILED: dumping logs` are within the test container?

<details>
<summary>Shell output</summary>

```sh
docker run --rm \
                -e TAG=branch-test_deploy_improvements \
                -e TRITON_PROFILE=joyent \
                -e GIT_BRANCH=test_deploy_improvements \
                -v ~/.ssh:/root/.ssh:ro \
                -v ~/.triton/profiles.d:/root/.triton/profiles.d:ro \
                -w /src \
                autopilotpattern/consul-testrunner:branch-test_deploy_improvements /src/triton.sh
Unable to find image 'autopilotpattern/consul-testrunner:branch-test_deploy_improvements' locally
branch-test_deploy_improvements: Pulling from autopilotpattern/consul-testrunner
cfc728c1c558: Pull complete
fa723a421920: Pull complete
413595a56645: Pull complete
5b37d6ff413c: Pull complete
c17f66a715e4: Pull complete
d16d83754e65: Pull complete
94f88637be99: Pull complete
0df64c8bf9c1: Pull complete
0c367c58ad21: Pull complete
224c7e4fce5f: Pull complete
Digest: sha256:536126f7352ea8a306df32bcf6d0afb60dd50d48155dc22b219716f3bcda1970
Status: Downloaded newer image for autopilotpattern/consul-testrunner:branch-test_deploy_improvements

------------------------------------------------
setting up profile for tests
------------------------------------------------

"joyent" is already the current profile

------------------------------------------------
FAILED: dumping logs
------------------------------------------------
triton account get: error (ENXIO): ENXIO: no such device or address, open '/dev/tty'
Couldn't find env file: /src/_env
make: *** [test/triton] Error 1
```

</details>

**Comment by jwreagor** [comment]
Obviously I should have looked at the `makefile` on that first one but I'm curious about the second error.

**Comment by tgross** [comment]
> Having unset my docker env vars I was able to at least build the test container but then received the following...

There shouldn't be a pull of `autopilotpattern/consul-testrunner:branch-test_deploy_improvements` going on at all. `TRITON_PROFILE=(whatever) make build/tester test/triton` should build the tester in Docker locally and then run it in Docker locally against Triton with the correct tags.

```
------------------------------------------------
FAILED: dumping logs
------------------------------------------------
triton account get: error (ENXIO): ENXIO: no such device or address, open '/dev/tty'
Couldn't find env file: /src/_env
make: *** [test/triton] Error 1
```

Those dumped logs are from `docker-compose logs`, but you never get far enough to have any logs if the test runner blows up because it isn't writing the `_env` file. I think the test runner container image that you pulled is broken because it doesn't have the latest commits, so get that building locally correctly first and you should be good-to-go.

**Comment by jwreagor** [comment]
Understandable that I need to build first.

**Comment by tgross** [comment]
Should be all done at this point.

**Review by jwreagor — APPROVED** [review]
LGTM, I ran all the tests locally and everything passed as anticipated.

**Pull request merged**
